Add small example script
devolo/ssllabs pull request #34
Opened 2023-03-16 11:31 UTC by Shutgun

Add a small example script, mainly based on #32.

2023-03-16 19:17 UTC, 2Fake requested changes

2023-03-16 19:17 UTC, 2Fake commented on README.md
> +If you are just interested in the grade of servers, you can take [this example](https://github.com/devolo/ssllabs/blob/master/example.py) as s stating point. Just exchange the list of hosts you want
```suggestion
If you are just interested in the grade of servers, you can take [this example](https://github.com/devolo/ssllabs/blob/master/example.py) as s starting point. Just exchange the list of hosts you want to query.
```

2023-03-16 19:18 UTC, 2Fake requested changes

2023-03-16 19:18 UTC, 2Fake commented on README.md
> +If you are just interested in the grade of servers, you can take [this example](https://github.com/devolo/ssllabs/blob/master/example.py) as s starting point. Just exchange the list of hosts you want
```suggestion
If you are just interested in the grade of servers, you can take [this example](https://github.com/devolo/ssllabs/blob/master/example.py) as a starting point. Just exchange the list of hosts you want to query.
```

2023-03-16 19:19 UTC, 2Fake approved these changes

2023-03-16 19:19 UTC, merged

2024-02-29 10:21 UTC, malavolti commented
Version in use: 1.2.1

Code affected:

```python
async def analyze(hosts: List[str]) -> List[HostData]:
    """Analyze servers."""
    ssllabs = Ssllabs()
    if not await ssllabs.availability():
        raise
    return await asyncio.gather(*[ssllabs.analyze(host=host,from_cache=True, max_age=1) for host in hosts])
```

GET generated: 
`2024-02-29 11:12:21,204: HTTP Request: GET https://api.ssllabs.com/api/v3/analyze?host=filesender.garr.it&startNew=on&fromCache=off&publish=off&ignoreMismatch=off&maxAge= "HTTP/1.1 200 "`

Seems that "**from_cache**"  parameter doesn't work.

Can you help me, please?

2024-02-29 10:41 UTC, Shutgun commented
Interesting ... I'm not seeing that here. Are you sure with the installed version or is maybe a virtual environment in your way?

`2024-02-29 11:38:37,534 httpx INFO: HTTP Request: GET https://api.ssllabs.com/api/v3/analyze?host=devolo.de&startNew=off&fromCache=on&publish=off&ignoreMismatch=off&maxAge=1 "HTTP/1.1 200`

2024-02-29 10:55 UTC, malavolti commented
I'm using a VirtualEnvironment to test all.

My VirtualEnv has pip 23.3.1 with:

ssllabs                       1.2.1

2024-02-29 12:23 UTC, Shutgun commented
Could you maybe try the following in your script?

```python
from ssllabs import __version__

print(__version__)
```

2024-02-29 12:39 UTC, malavolti commented
```
$ python3 ssllabs-version.py

1.2.1
```

2024-02-29 12:57 UTC, Shutgun commented
I don't know what going on... If I execute this:

```python
"""Get grade of multiple servers."""
import asyncio
import logging
from typing import List

from ssllabs import Ssllabs, __version__
from ssllabs.data.host import HostData

HOSTS = [
    "devolo.com",
    "www.devolo.com",
]


async def analyze(hosts: List[str]) -> List[HostData]:
    """Analyze servers."""
    ssllabs = Ssllabs()
    if not await ssllabs.availability():
       raise
    return await asyncio.gather(*[ssllabs.analyze(host=host, from_cache=True, max_age=1) for host in hosts])


if __name__ == "__main__":
    print(__version__)
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(name)s %(levelname)s: %(message)s")
    results = asyncio.run(analyze(HOSTS))
    for result in results:
        for endpoint in result.endpoints:
            if endpoint.grade:
                logging.info(
                    "Grade of %s (%s): %s",
                    result.host,
                    endpoint.ipAddress,
                    endpoint.grade,
                )
            else:
                logging.error(endpoint.statusMessage)
```
I get:
```
1.2.1
2024-02-29 13:54:44,984 httpx INFO: HTTP Request: GET https://api.ssllabs.com/api/v3/info "HTTP/1.1 200 "
2024-02-29 13:54:44,985 ssllabs.Ssllabs INFO: SSL Labs servers are up an running.
2024-02-29 13:54:44,985 ssllabs.Ssllabs INFO: Analyzing devolo.com
2024-02-29 13:54:45,532 httpx INFO: HTTP Request: GET https://api.ssllabs.com/api/v3/info "HTTP/1.1 200 "
2024-02-29 13:54:46,078 httpx INFO: HTTP Request: GET https://api.ssllabs.com/api/v3/analyze?host=devolo.com&startNew=off&fromCache=on&publish=off&ignoreMismatch=off&maxAge=1 "HTTP/1.1 200 "
2024-02-29 13:54:46,080 ssllabs.Ssllabs INFO: Analyzing www.devolo.com
2024-02-29 13:54:46,608 httpx INFO: HTTP Request: GET https://api.ssllabs.com/api/v3/info "HTTP/1.1 200 "
2024-02-29 13:54:47,141 httpx INFO: HTTP Request: GET https://api.ssllabs.com/api/v3/analyze?host=www.devolo.com&startNew=off&fromCache=on&publish=off&ignoreMismatch=off&maxAge=1 "HTTP/1.1 200 "
2024-02-29 13:54:47,143 root INFO: Grade of devolo.com (195.201.179.93): B
2024-02-29 13:54:47,143 root INFO: Grade of devolo.com (159.69.77.193): B
2024-02-29 13:54:47,143 root INFO: Grade of devolo.com (159.69.96.138): B
2024-02-29 13:54:47,143 root INFO: Grade of www.devolo.com (159.69.77.193): B
2024-02-29 13:54:47,143 root INFO: Grade of www.devolo.com (195.201.179.93): B
2024-02-29 13:54:47,143 root INFO: Grade of www.devolo.com (159.69.96.138): B
```

2024-02-29 13:16 UTC, 2Fake commented
It would be better to open up an issue on that please.

________________________________
From: Guido Schmitz ***@***.***>
Sent: Thursday, February 29, 2024 1:57:55 PM
To: devolo/ssllabs ***@***.***>
Cc: Markus Bong ***@***.***>; State change ***@***.***>
Subject: Re: [devolo/ssllabs] Add small example script (PR #34)


I don't know what going on... If I execute this:

"""Get grade of multiple servers."""
import asyncio
import logging
from typing import List

from ssllabs import Ssllabs, __version__
from ssllabs.data.host import HostData

HOSTS = [
    "devolo.com",
    "www.devolo.com",
]


async def analyze(hosts: List[str]) -> List[HostData]:
    """Analyze servers."""
    ssllabs = Ssllabs()
    if not await ssllabs.availability():
       raise
    return await asyncio.gather(*[ssllabs.analyze(host=host, from_cache=True, max_age=1) for host in hosts])


if __name__ == "__main__":
    print(__version__)
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(name)s %(levelname)s: %(message)s")
    results = asyncio.run(analyze(HOSTS))
    for result in results:
        for endpoint in result.endpoints:
            if endpoint.grade:
                logging.info(
                    "Grade of %s (%s): %s",
                    result.host,
                    endpoint.ipAddress,
                    endpoint.grade,
                )
            else:
                logging.error(endpoint.statusMessage)

I get:

1.2.1
2024-02-29 13:54:44,984 httpx INFO: HTTP Request: GET https://api.ssllabs.com/api/v3/info "HTTP/1.1 200 "
2024-02-29 13:54:44,985 ssllabs.Ssllabs INFO: SSL Labs servers are up an running.
2024-02-29 13:54:44,985 ssllabs.Ssllabs INFO: Analyzing devolo.com
2024-02-29 13:54:45,532 httpx INFO: HTTP Request: GET https://api.ssllabs.com/api/v3/info "HTTP/1.1 200 "
2024-02-29 13:54:46,078 httpx INFO: HTTP Request: GET https://api.ssllabs.com/api/v3/analyze?host=devolo.com&startNew=off&fromCache=on&publish=off&ignoreMismatch=off&maxAge=1 "HTTP/1.1 200 "
2024-02-29 13:54:46,080 ssllabs.Ssllabs INFO: Analyzing www.devolo.com
2024-02-29 13:54:46,608 httpx INFO: HTTP Request: GET https://api.ssllabs.com/api/v3/info "HTTP/1.1 200 "
2024-02-29 13:54:47,141 httpx INFO: HTTP Request: GET https://api.ssllabs.com/api/v3/analyze?host=www.devolo.com&startNew=off&fromCache=on&publish=off&ignoreMismatch=off&maxAge=1 "HTTP/1.1 200 "
2024-02-29 13:54:47,143 root INFO: Grade of devolo.com (195.201.179.93): B
2024-02-29 13:54:47,143 root INFO: Grade of devolo.com (159.69.77.193): B
2024-02-29 13:54:47,143 root INFO: Grade of devolo.com (159.69.96.138): B
2024-02-29 13:54:47,143 root INFO: Grade of www.devolo.com (159.69.77.193): B
2024-02-29 13:54:47,143 root INFO: Grade of www.devolo.com (195.201.179.93): B
2024-02-29 13:54:47,143 root INFO: Grade of www.devolo.com (159.69.96.138): B


—
Reply to this email directly, view it on GitHub<https://github.com/devolo/ssllabs/pull/34#issuecomment-1971085513>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AEHIZNPFPNFZQPGWKUKZIZDYV4SVHAVCNFSM6AAAAAAV5CQMX2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNZRGA4DKNJRGM>.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

2024-02-29 13:22 UTC, 2Fake commented
I just recreated your request with your data to ensure that there isn't something strange with your URL provided. I get the expected result with the result provided from cache. 
Could you test it with provided devcontainer to be sure that your environment is the same as ours?

`2024-02-29 13:19:53,339 httpx INFO: HTTP Request: GET https://api.ssllabs.com/api/v3/analyze?host=filesender.garr.it&startNew=off&fromCache=on&publish=off&ignoreMismatch=off&maxAge=1 "HTTP/1.1 200 "`

2024-02-29 15:08 UTC, malavolti commented
I'll try, thank you all. :)